PROJECT/export/fame/urls.py
from django.urls import path

from fame.views.html import fame_list
from fame.views.rest import ExpertiseAreasApiView, FameUsersApiView, FameListApiView

app_name = "fame"

urlpatterns = [
    path(
        "api/expertise_areas", ExpertiseAreasApiView.as_view(), name="expertise_areas"
    ),
    path("api/users", FameUsersApiView.as_view(), name="fame_users"),
    path("api/fame", FameListApiView.as_view(), name="fame_fulllist"),
    path("html/fame", fame_list, name="fame_list"),
]

PROJECT/export/famesocialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include

from famesocialnetwork.views.html import home, MyLogoutView, MyLoginView

urlpatterns = [
    path(
        "",
        MyLoginView.as_view(
            template_name="login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path(
        "logout/",
        MyLogoutView.as_view(
            template_name="logged_out.html",
            next_page="/",
        ),
        name="logout",
    ),
    path("home/", home, name="home"),
    path("admin/", admin.site.urls),
    path("fame/", include("fame.urls", namespace="fame")),  # reroute to fame app
    path(
        "sn/", include("socialnetwork.urls", namespace="sn")
    ),  # reroute to social network app
]

PROJECT/export/socialnetwork/urls.py
from django.urls import path

from socialnetwork.views.html import timeline, toggle_community_mode, join_community, leave_community, bullshitters, similar_users
from socialnetwork.views.html import follow
from socialnetwork.views.html import unfollow
from socialnetwork.views.rest import PostsListApiView

app_name = "socialnetwork"

urlpatterns = [
    path("api/posts", PostsListApiView.as_view(), name="posts_fulllist"),
    path("html/timeline", timeline, name="timeline"),
    path("html/toggle_community_mode", toggle_community_mode, name="toggle_community_mode"),
    #linking bullshitters with the given urlpattern
    path("html/bullshitters", bullshitters, name="bullshitters"),
    path("html/similar_users", similar_users, name="similar_users"),
    path("html/join_community", join_community, name="join_community"),
    path("html/leave_community", leave_community, name="leave_community"),
    path("api/follow", follow, name="follow"),
    path("api/unfollow", unfollow, name="unfollow"),
]

PROJECT/export/socialnetwork/models.py
import random as rnd

from django.contrib.auth.models import AbstractUser
from django.db import models

from fame.models import ExpertiseAreas, FameUsers
from socialnetwork.magic_AI import classify_into_expertise_areas_and_check_for_bullshit

rnd.seed(42)


class SocialNetworkUsers(FameUsers):
    """Users of the social network."""

    follows = models.ManyToManyField(
        "self", symmetrical=False, related_name="followed_by" #self means SocialNetworkUsers
        #symmetrical=False: one user following another does not mean that the other user follows the first one
    )
    is_banned = models.BooleanField(default=False)
    # T4
    # use this member field to adapt the data model, DO NOT RENAME!
    #creating a field-definition object using the constructor call models.ManyToManyField(...)
    communities  = models.ManyToManyField(
        ExpertiseAreas,
        blank=True,  # a user can have no area of expertise (need living proof?)
        related_name="community_members" #represents the name of the reversed relation from communities to members (i.e. from members to communities)
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.email})"

    class Meta:
        db_table = "social_network_users"


class Posts(models.Model):
    """Posts in the social network."""

    content = models.CharField(max_length=42 * 42, null=False)
    author = models.ForeignKey("SocialNetworkUsers", on_delete=models.CASCADE)
    submitted = models.DateTimeField(auto_now_add=True)

    cites = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="cited_by"
    )
    replies_to = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="replied_to",
    )

    expertise_area_and_truth_ratings = models.ManyToManyField(
        ExpertiseAreas,
        symmetrical=False,
        related_name="classified_as",
        through="PostExpertiseAreasAndRatings",
    )
    user_ratings = models.ManyToManyField(
        SocialNetworkUsers,
        symmetrical=False,
        related_name="rated_by",
        through="UserRatings",
    )

    published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-submitted"]
        unique_together = ("author", "submitted")
        db_table = "posts"

    def determine_expertise_areas_and_truth_ratings(self):
        # ask the mighty AI to classify_into_expertise_areas the content into expertise areas:
        _expertise_areas = classify_into_expertise_areas_and_check_for_bullshit(
            self.content
        )

        # create the expertise areas and truth ratings:
        at_least_one_expertise_area_contains_bullshit = False

        for epa in _expertise_areas:
            PostExpertiseAreasAndRatings.objects.create(
                post=self,
                expertise_area=epa["expertise_area"],
                truth_rating=epa["truth_rating"],
            )
            if epa["truth_rating"] and epa["truth_rating"].numeric_value < 0:
                at_least_one_expertise_area_contains_bullshit = True

        return at_least_one_expertise_area_contains_bullshit, _expertise_areas

    def __str__(self):
        return f"{self.author} - {self.submitted} - {self.content[:10]}..."


class TruthRatings(models.Model):
    """Ratings of the truthfulness of a post. Not to be confused with ExpertiseAreas!"""

    name = models.CharField(max_length=42)
    numeric_value = models.IntegerField(null=False)

    def __str__(self):
        return f"{self.name} ({self.numeric_value})"

    class Meta:
        db_table = "truth_ratings"


class PostExpertiseAreasAndRatings(models.Model):
    """Expertise areas and truth ratings determined for the contents of a post."""

    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    expertise_area = models.ForeignKey(ExpertiseAreas, on_delete=models.CASCADE)
    truth_rating = models.ForeignKey(TruthRatings, on_delete=models.CASCADE, null=True)

    class Meta:
        unique_together = ("post", "expertise_area")

    def __str__(self):
        return f"{self.post} - {self.expertise_area} - {self.truth_rating}"

    class Meta:
        db_table = "post_expertise_areas_and_ratings"


class UserRatings(models.Model):
    """User ratings and/or approvals of a post."""

    APPROVAL = "A"
    LIKE = "L"
    DISLIKE = "D"
    RATING_TYPES = [(APPROVAL, "Approval"), (LIKE, "Like"), (DISLIKE, "Dislike")]

    user = models.ForeignKey(SocialNetworkUsers, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    score = models.IntegerField()
    type = models.CharField(
        max_length=1,
        choices=RATING_TYPES,
        default=LIKE,
    )

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "post", "type")

    def __str__(self):
        return f"{self.user} - {self.post} - {self.type} - {self.score}"

PROJECT/export/socialnetwork/views/html.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from socialnetwork import api
from socialnetwork.api import _get_social_network_user
from socialnetwork.models import SocialNetworkUsers
from socialnetwork.serializers import PostsSerializer
from fame.models import Fame, ExpertiseAreas


@require_http_methods(["GET", "POST"])
@login_required
def timeline(request):
    # using the serializer to get the data, then use JSON in the template!
    # avoids having to do the same thing twice
    user=_get_social_network_user(request.user)
    # initialize community mode to False the first time in the session
    if 'community_mode' not in request.session:
        request.session['community_mode'] = False

    is_community_mode = request.session['community_mode']  #read mode from session

    communities_joined = []
    available_communities_not_joined = [] # by default empty
    if is_community_mode:
        communities_joined = list(user.communities.all().values_list("label", flat=True).distinct())

        #this will be a list of IDs(!) of corresponding expertise areas
        eligible_communities_area_ids = list(Fame.objects.filter(user=user, fame_level__numeric_value__gte=100).all()
                                .values_list("expertise_area_id", flat=True).distinct()) #100 is super pro

        #now again we want a list with labels instead of IDs
        for potential_community_area_id in eligible_communities_area_ids:
            potential_community_name = (ExpertiseAreas.objects.filter(id=potential_community_area_id)
                                        .values_list("label", flat=True).first()) #first element of the queryset (and the only one)
            #expertiseareas is an automatically generated field, because it's foreign key in communities

            if (potential_community_name not in communities_joined
                    and potential_community_name not in available_communities_not_joined): #we don't want the same community twice
                    available_communities_not_joined.append(potential_community_name)
    #if standard mode, the communities lists will stay empty.
    #We could still fill them with respective communities because we built timeline.html the way
    #that it doesn't show the communities in standard mode
    #but for performance it will be better not to fill the communities in standard mode


    # get extra URL parameters:
    keyword = request.GET.get("search", "")
    published = request.GET.get("published", True)
    error = request.GET.get("error", None)


    # if keyword is not empty, use search method of API:
    if keyword and keyword != "":
        context = {
            "communities_joined": communities_joined,
            "available_communities_not_joined": available_communities_not_joined,
            "posts": PostsSerializer(
                api.search(keyword, published=published), many=True
            ).data, #so far I am not changing it
            "searchkeyword": keyword,
            "error": error,
            "followers": list(api.follows(user).values_list('id', flat=True)),
        }
    else:  # otherwise, use timeline method of API:
        context = {
            "communities_joined": communities_joined,
            "available_communities_not_joined": available_communities_not_joined,
            "posts": PostsSerializer(
                api.timeline(
                    user,
                    published=published,
                    community_mode=is_community_mode
                ),
                many=True,
            ).data,
            "searchkeyword": "",
            "error": error,
            "followers": list(api.follows(user).values_list('id', flat=True)),
        }
    return render(request, "timeline.html", context=context)

@require_http_methods(["POST"])
@login_required
def follow(request):
    user = _get_social_network_user(request.user)
    user_to_follow = SocialNetworkUsers.objects.get(id=request.POST.get("user_id"))
    api.follow(user, user_to_follow)
    return redirect(reverse("sn:timeline"))


@require_http_methods(["POST"])
@login_required
def unfollow(request):
    user = _get_social_network_user(request.user)
    user_to_unfollow = SocialNetworkUsers.objects.get(id=request.POST.get("user_id"))
    api.unfollow(user, user_to_unfollow)
    return redirect(reverse("sn:timeline"))


#T6
#we will "toggle" bullshitters mode (the button either shows or hides the list
@require_http_methods(["GET"])
@login_required
def bullshitters(request):
    context={
            "bullshitters": api.bullshitters(),
    }
    return render(request, "bullshitters.html", context=context)


#T7
@require_http_methods(["POST"])
@login_required
def toggle_community_mode(request):
    current = request.session.get("community_mode", False) #false is default
    request.session["community_mode"] = not current
    return redirect(reverse("sn:timeline"))  # redirect back to timeline after toggling


@require_http_methods(["POST"])
@login_required
def join_community(request):
    community_name = request.POST.get("community")
    community = ExpertiseAreas.objects.get(label=community_name)
    user = _get_social_network_user(request.user)
    api.join_community(user, community)
    return redirect(reverse("sn:timeline"))

@require_http_methods(["POST"])
@login_required
def leave_community(request):
    community_name=request.POST.get("community")
    community = ExpertiseAreas.objects.get(label = community_name)
    user = _get_social_network_user(request.user)
    api.leave_community(user, community)
    return redirect(reverse("sn:timeline"))

#T8
@require_http_methods(["GET"])
@login_required
def similar_users(request):
    user = _get_social_network_user(request.user)
    context = {
        "similar_users": api.similar_users(user),
    }
    return render(request, "similar_users.html", context=context)

PROJECT/export/socialnetwork/views/rest.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse
from rest_framework import status, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from socialnetwork import api
from socialnetwork.api import timeline, _get_social_network_user
from socialnetwork.serializers import PostsSerializer


class PostsListApiView(APIView):
    # check permission if user is authenticated
    permission_classes = [permissions.IsAuthenticated]

    # 1. List all social network posts through a GET call
    def get(self, request, *args, **kwargs):
        """
        List all posts items
        """
        posts = timeline(_get_social_network_user(request.user))
        serializer = PostsSerializer(posts, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    # 2. Create a post in the social network through a POST call
    def post(self, request, *args, **kwargs):
        ret, _expertise_areas, redirect_to_logout = api.submit_post(
            user=_get_social_network_user(request.user),
            content=request.data.get("text"),
        )
        if redirect_to_logout:
            logout(request)
            assert request.user.is_authenticated is False
            return redirect(reverse("login"))

        assert request.user.is_authenticated is True
        return redirect(reverse("sn:timeline"))

PROJECT/export/socialnetwork/templates/base.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="text/html"/>
    <title>{% block title %}Default title{% endblock %}</title>
    <link
            rel="stylesheet"
            href="{% static 'bootstrap.min.css' %}"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'bootstrap-icons.css' %}"
    />
    <link
            rel="stylesheet"
            href="{% static 'fa/css/all.min.css' %}"
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    />
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body class="d-flex flex-column min-vh-100">

<div class="body-content">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="navbar-brand" href="{% url 'sn:timeline' %}">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="navbar-brand" href="{% url 'home' %}">URIs</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" data-testid="navbar_user_section">
                        {% if user.is_authenticated %}
                            <span>{{ request.user.first_name }} {{ request.user.last_name }}</span>
                        {% else %}
                            <span>Not logged in</span>
                        {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    </div>
            </ul>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">logout</button>
                </form>
            {% endif %}
        </nav>
    </header>

    <div id="wrap">
        <div class="container-fluid" id="main">
            {% block body %} {% endblock %}
        </div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %} {% endblock %}

    <footer
            class="page-footer fixed-bottom font-small bg-dark pt-1"
            style="color: gray"
    >
        <div style="display: flex; justify-content: space-between">
            <div style="margin-left: 10px; margin-right: 10px">Fame Social Network</div>
            <div style="margin-right: 10px">
                <a
                        style="color: gray"
                        href="https://www.uni-saarland.de/en/legal-notice.html"
                        data-testid="footer_impressum"
                >Impressum/Legal Notice</a>
            </div>
        </div>
    </footer>

</div>
</body>
</html>

PROJECT/export/socialnetwork/templates/bullshitters.html
{% extends "base.html" %}

{% load static %}

{% block title %}Bullshitters{% endblock %}

{% block body %}
    {# button to return to timeline #}
    <div style="margin: 20px;">
    <a href="{% url 'sn:timeline' %}" class="btn btn-primary">  {# a is a link made into a form of a button #}
            Back to Timeline
    </a>
    </div>

    {# Showing bullshitters#}
    <h3 style="margin-left: 40px">Bullshitters:</h3>
        {% for area, bullshitters_in_area in bullshitters.items %}  <! -- iterating over bullshitters using .items to directly map keys and values -->
            <h4 style="margin-left: 40px">{{ area.label }}</h4>  <! -- heading of the display is area -->
            <ul>
            {% for entry in bullshitters_in_area %}  <! -- iterating over bullshitters in that area -->
                <li style="margin-left: 40px">
                {{ entry.user.username }} - {{ entry.user.first_name }} {{ entry.user.last_name }} <! -- displaying bullshitters' username. firstname and lastname -->
                <br>
                </li>
            {% endfor %}
            </ul>
            {% empty %} {# exception handling #}
            <p style="margin-left: 40px">No bullshitters found.</p>    <! -- info display if no bullshitters exist in some particular area -->
        {% endfor %}
    <br><br>

{% endblock %}

PROJECT/export/socialnetwork/templates/logged_out.html
<head>
    <title>Login</title>
</head>
<body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

You were successfully logged out!

<a href="/">Back to login</a>
</body>

PROJECT/export/socialnetwork/templates/login.html
{% extends "base.html" %}

{% load static %}

{% block title %}TimelFame Social Network: Available URIsine{% endblock %}

{% block body %}
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Email</label>
        <input type="text" name="username" id="">
        <label for="">Password</label>
        <input type="password" name="password" id="">
        <button type="submit" class="btn btn-secondary">Login</button>
    </form>
    <br>
    If in doubt, use the following credentials:<br>
    email: a@b.de<br>
    password: test
{% endblock %}

PROJECT/export/socialnetwork/templates/similar_users.html
{% extends "base.html" %}

{% load static %}

{% block title %}Similar users{% endblock %}

{% block body %}
    <!-- button to return to timeline -->
    <div style="margin: 20px;">
    <a href="{% url 'sn:timeline' %}" class="btn btn-primary">  {# a is a link made into a form of a button #}
        Back to Timeline
    </a>
    </div>

<!-- Showing similar_users -->
        <h6 style="margin-left: 40px">
        The users are sorted from the most similar to you to the least similar.
        Note: only users with non-zero similarity score are shown.
        </h6>
        <h3 style="margin-left: 40px">Users similar to me:</h3>
    {% for user in similar_users %}  <! -- iterating over similar_users-->
        <li style="margin-left: 40px">
          {{ user.username }} - {{ user.first_name }} {{ user.last_name }} <! -- displaying similar_users' username. firstname and lastname -->
            <br>
        </li>
        {% empty %}
            <p style="margin-left: 40px">No similar_users found.</p>    <! -- info display if no similar_users exist -->
    {% endfor %}
    <br><br>
    
{% endblock %}

PROJECT/export/socialnetwork/templates/timeline.html
{% extends "base.html" %}

{% load static %}
{% load highlight %}

{% block title %}Timeline{% endblock %}

{% block body %}
    <!-- button to change the mode -->
    <div style="margin: 20px;">
        <form action="/sn/html/toggle_community_mode" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">
                {% if request.session.community_mode %}
                    Switch to Normal Mode
                {% else %}
                    Switch to Community Mode
                {% endif %}
            </button>
        </form>
    </div>
    <!-- button to show bullshitters -->
    <div style="margin: 20px;">
    <a href="{% url 'sn:bullshitters' %}" class="btn btn-primary">  {# a is a link made into a form of a button #}
            Show Bullshitters
    </a>
    </div>

        <!-- button to show similar_users -->
    <div style="margin: 20px;">
    <a href="{% url 'sn:similar_users' %}" class="btn btn-primary">  {# a is a link made into a form of a button #}
        Show similar users
    </a>
    </div>



    <br>
    <div class="card"
         style="margin-bottom: 20px; border-color: white; width: 300px; margin-left: auto; margin-right: 40px;">
        <form action="/sn/html/timeline" method="get">
            <div class="flex-container">
                <input type="text" name="search" placeholder={{ searchkeyword }}>
                <button type="submit" class="btn btn-secondary">Search</button>
            </div>
        </form>
    </div>
    <br>
    <div class="card" style="margin-bottom: 20px; margin-left: 40px; margin-right: 40px;">
        <form action="/sn/api/posts" method="post">
            {% csrf_token %}
            <textarea class="form-control" rows="5" name="text"></textarea>
            <button type="submit" class="btn btn-secondary">Post</button>
        </form>
    </div>
    <br>
    <br>
    <h3 style="margin-left: 40px">Timeline</h3>
     <br>







    <!-- Part that is only for community mode -->
    {% if request.session.community_mode %}
        <!-- Button to leave a community -->
    <h5 style="margin-left: 40px">My communities:</h5>

    {% for community in communities_joined %}
    <form action="/sn/html/leave_community" method="post" style="display: inline;"> <!-- inline - in the same line -->
        {% csrf_token %}
        <input type="hidden" name="community" value="{{ community }}">
        <div class="d-flex align-items-center mb-2">
            <button type="submit" class="btn btn-secondary me-2" style="background-color:red; margin-left: 40px">Leave</button>
            <span>{{ community }}</span>
        </div>
    </form>
    {% endfor %}

    <!-- Button to join a community -->
    <br>

    <h5 style="margin-left: 40px">Communities I can join:</h5>

    {% for community in available_communities_not_joined %}
    <form action="/sn/html/join_community" method="post" style="display: inline;"> <!-- inline - in the same line -->
        {% csrf_token %}
        <input type="hidden" name="community" value="{{ community }}">
        <div class="d-flex align-items-center mb-2">
            <button type="submit" class="btn btn-secondary me-2" style="background-color:green; margin-left: 40px">Join</button>
            <span>{{ community }}</span>
        </div>
    </form>
    {% endfor %}
    <br>
    {% endif %}


    {% for post in posts %}
        <div class="card"
             style="margin-bottom: 20px; margin-left: 40px; margin-right: 40px; background-color: {% if post.published %}white{% else %}mistyrose{% endif %};">
            <div class="flex-container">
                <b><a href="/fame/html/fame?userid={{ post.author.id }}">{{ post.author.name|highlight:searchkeyword }}
                </b></a>&nbsp;
                <span style="color:gray">{{ post.author.email|highlight:searchkeyword }}</span>&nbsp;&nbsp;
                <span style="color:gray">{{ post.date_submitted }}</span>
                {% if not post.published %}
                    <span style="color:red">&nbsp;[not published, only visible for you]</span>
                {% endif %}
                {% if post.published and post.author.id == request.user.id %}
                    <span style="color:green">&nbsp;[published, visible for everybody]</span>
                {% endif %}
            </div>&nbsp;<br>
            <p>{{ post.content|highlight:searchkeyword }}</p>

            <div class="flex-container">
                {% for key,value in post.expertise_area_and_truth_ratings.items %}
                    {% if value.numeric_value < 0 %}
                        <div class="bullshit"><b>{{ key }}</b>: {{ value.name }}</div>
                    {% elif value.numeric_value > 0 %}
                        <div class="ok"><b>{{ key }}</b>: {{ value.name }}</div>
                    {% else %}
                        <div class="neutral"><b>{{ key }}</b>: {{ value.name }}</div>
                    {% endif %}
                {% endfor %}<br>
            </div>
            <div class="flex-container">
                <div><i class="fa-regular fa-comment" style="color:gray;"></i> {{ post.citations }}</div>
                <div><i class="fa-solid fa-retweet" style="color:gray;"></i> {{ post.replies }}</div>
                {% for key,value in post.user_ratings.items %}
                    {% if key == "A" %}
                        <div><i class="fa-solid fa-thumbs-up" style="color:blue;"></i>&nbsp;{{ value }}</div>
                    {% elif key == "L" %}
                        <div><i class="fa-solid fa-heart" style="color:green;"></i>&nbsp;{{ value }}</div>
                    {% elif key == "D" %}
                        <div><i class="fa-solid fa-thumbs-down" style="color:red;"></i> {{ value }}</div>
                    {% endif %}
                {% endfor %}
                <div><i class="fa-solid fa-chart-simple" style="color:gray;"></i> 0</div>
            </div>
        </div>
    {% endfor %}
    <br><br>

{% endblock %}